### ISSUE TITLE
Side Specific Proxy breaks in Firefox

### ISSUE THREAD

**Issue by MNarath1** [mullvad/browser-extension#203] opened 2024-03-23 08:53 UTC
In my case the side specific proxy only shows for youtube.com no matter what side i visit and will not allow any other sites to be set for side specific proxy. It works perfectly fine in the mullvad browser.
This behavior also persists between removing and reinstalling the plugin (suggests that those files don't get deleted????)
Current Firefox Version 124.0.1
OS: Linux

**Comment by MNarath1** [comment] 2024-03-23 08:57
Current Firefox Version 124.0.1

**Comment by ruihildt** [comment] 2024-03-23 09:52
When you uninstall, it seems settings are kept.
We should probably explore cleaning up proxy settings on uninstall or offer a way to reset the extension settings.

There is a way to reset, but please bear in mind this will **delete your current proxy settings**, and you will be connecting to the internet through you current system connection.

- go to `about:debugging#/runtime/this-firefox`
- scroll until `Mullvad Browser Extension` and click on `Inspect`
- the `Developer Tools` window opens
- click on the `Storage` tab
- on the left menu, click on `Extension Storage`
- under `Extension Storage`, another line expands starting with `moz-extension://...`
- right click on it
- click `Delete all`

**Comment by ruihildt** [comment] 2024-03-23 09:55
I opened #204

**Comment by MNarath1** [comment] 2024-03-23 21:14
The bug just randomly vanished for no apperant reasons trough yes deleting the settings is probably a good idea after uninstall

**Comment by ruihildt** [comment] 2024-03-25 12:08
It does seem like it's the same bug. I'll close this as a duplicate of #198. 

Thanks!

**Closed by ruihildt** 2024-03-25 12:08 UTC
Labels: duplicate
