### ISSUE TITLE
[Bug] Extension does not detect I am connected to WireGuard

### ISSUE THREAD

**Issue by MrChocolatine** [mullvad/browser-extension#195] opened 2024-03-07 10:48 UTC
## Context / Bug

See this video:

https://github.com/mullvad/browser-extension/assets/47531779/2990c5ab-becc-4283-83f7-23930708a1d0

## Info

- Mullvad Browser v13.0.10
- Mullvad Browser Extension: v0.9.0

**Comment by ruihildt** [comment] 2024-03-07 10:52
As this is related to the Mullvad Browser Extension, this is the right place. :)
It seems that the proxy location is the cause of the error. 

Can you confirm using `be-bru-wg-socks5-101` works for you?

**Comment by MrChocolatine** [comment] 2024-03-07 10:58
> Can you confirm using `be-bru-wg-socks5-101` works for you?

Ah yes, looks like if I manually select this one it works.

- Proxy Server: be-bru-wg-101 => works
- Proxy Server: be-bru-wg-102 => works
- Proxy Server: be-bru-wg-103 => does not work

For the record, you see I use proxies based in Belgium but this is random, I could have used any other country.

**Comment by ruihildt** [comment] 2024-03-07 11:00
The bug seems to be specific to this proxy exit, I have reported that internally.

**Comment by ruihildt** [comment] 2024-03-07 11:48
The issues is not with the extensions, but with a proxy server. So I will close the issue.

**Closed by ruihildt** 2024-03-07 11:48 UTC
Labels: bug, proxy

**Comment by MrChocolatine** [comment] 2024-03-07 13:47
> The issues is not with the extensions, but with a proxy server. So I will close the issue.

👍
