### ISSUE TITLE
[Feature] Wildcard URLs/Website Proxy Settings

### ISSUE THREAD

**Issue by ncorder** [mullvad/browser-extension#235] opened 2024-09-08 08:29 UTC
Hello everyone,
    I am attending University in the United States and many of the major websites for our university do not connect when utilizing certain Mullvad servers.

Because of this, I must set the location to London (one of the severs they do not appear to filter). This extension has made this much easier. However, they utilize many URLS.

Would it be possible to add wildcard functionality to URLs added to the extension? Something like stating that all "*.arizona.edu" domains will utilize a specific proxy?

Thank you so much for all of your time making such a wonderful extension.
—Best

**Comment by ruihildt** [comment] 2024-09-09 06:49
Hi, thanks for your feedback!

This is somewhat planned for the next version.

The behavior will be that when you add a domain for proxying, by default all of its subdomains will also use the same proxy.
And if you want specific subdomains to be proxied throgh different servers, you'll be able to override the default behavior.

**Comment by ruihildt** [comment] 2024-10-18 07:09
Closing as duplicate of #232

**Closed by ruihildt** 2024-10-18 07:09 UTC
Labels: duplicate
