### ISSUE TITLE
Connect to VPN server directly from browser without isntalled app

### ISSUE THREAD

**Issue by theLastOfCats** [mullvad/browser-extension#152] opened 2023-04-08 23:00 UTC
NordVPN has an browser extension which allows to connect to VPN without needing of standalone app. It'll be great if Mullvad allows same thing

**Comment by begin-theadventure** [comment] 2023-04-08 23:07
https://github.com/mullvad/browser-extension/issues/151

**Comment by ruihildt** [comment] 2023-04-08 23:45
Duplicate of #151.

**Closed by ruihildt** 2023-04-08 23:45 UTC
Labels: duplicate
