### ISSUE TITLE
Install-time `<all_urls>`  permission request

### ISSUE THREAD

**Issue by thpani** [mullvad/browser-extension#201] opened 2024-03-21 11:00 UTC
First, let me thank you for your excellent work on this extension!

Unfortunately, the 0.9.0 release requests `<all_urls>` permission at install-time via its manifest file. I'm not willing to grant this to any extension, much less one geared towards privacy.

I assume this permission is required for the new proxy functionalities. Please consider disabling these by default, and requesting `<all_urls>` only when the user enables them.

Until such time, I see no other way but to disable the Mullvad browser extension :(

**Comment by ruihildt** [comment] 2024-03-21 13:00
Closing as a duplicate of #16.

This is planned for the next version.

**Closed by ruihildt** 2024-03-21 13:00 UTC
